// Auth
export const TOKEN_CHANGED = 'TOKEN_CHANGE'
export const PROFILE_CHANGED = 'PROFILE_CHANGED'
export const PUSH_TOKEN_CHANGED = 'PUSH_TOKEN_CHANGED'

// App
export const SETTING_CHANGED = 'SETTING_CHANGED'
export const REFRESH_HISTORY_LOG = 'REFRESH_HISTORY_LOG'
export const NOTI_UNREAD_CHANGED = 'NOTI_UNREAD_CHANGED'
export const REFRESH_NOTI_LIST = 'REFRESH_NOTI_LIST'
export const REFRESH_NOTIFICATIONS_SETTING = 'REFRESH_NOTIFICATIONS_SETTING'
export const REFRESH_BOOKING_DETAIL = 'REFRESH_BOOKING_DETAIL'
export const REFRESH_PROFILE = 'REFRESH_PROFILE'
export const REFRESH_NEW_BOOKING = 'REFRESH_NEW_BOOKING'

export const LIST_COUNTRY = 'LIST_COUNTRY'

// Own Props
export const OWN_PROPS = 'OWN_PROPS2'

export const MENU_CHANGED = 'MENU_CHANGED'